### ISSUE TITLE
more message history

### ISSUE THREAD

**Issue by davidhq** [firebase/firechat#32]
I cannot find anywhere if it's possible to pass in some configuration option to FirechatUI so that there is more messages in chat window.... 

thank you

**Comment by greenido** [comment]
Any update on this?

**Comment by jwngr** [comment]
It looks like you can use the [undocumented `numMaxMessages` option](https://github.com/firebase/firechat/blob/893c6913a7316fc7d0be99f6297ef9d7d737e4d6/src/js/firechat.js#L59) when initializing Firechat. It would look like this:

```
var chat = new Firechat(chatRef, {
  numMaxMessages: 1000
});
```

I added this to the docs in PR #66 (commit here: https://github.com/firebase/firechat/pull/66/commits/08b04be09723d1818bbef3dd24d667d735c9cd35) which should get deployed next week.
