### ISSUE TITLE
Firebase account requirement

### ISSUE THREAD

**Issue by irwinj** [firebase/firechat#38]
Hello,
It appears that I need a firebase account to use fire chat. My questions:

1. Is my firechat limited to a specific number of concurrent users depending on my firebase account type (i.e. the candle plan has a limited of 200 connections. Does this pertain to fire chat also)?
2. If the answer to the above is no, can a hacker plan be used for firechat or is a paid account required?

Thank you,
Jason

**Comment by shortjared** [comment]
You will in fact need to have your own firebase account & plan. You can use the free Firebase hacker plan to power Firechat with no issue, with the assumption that 50 concurrent connections is enough for your use case.

**Comment by irwinj** [comment]
That's what I thought, thank you!
