### ISSUE TITLE
working phonegap example

### ISSUE THREAD

**Issue by DavePilks** [firebase/firechat#43]
Hi 

I am trying to get this to work using phonegap but I just cannot get it working. Do you guys perhaps have a working sample you can upload?

**Comment by katowulf** [comment]
We don't have any Firechat version for phonegap. Sorry.

**Comment by DavePilks** [comment]
What about this blog post then?

https://www.firebase.com/blog/2013-04-16-firebase-adds-phonegap-cordova-support.html

**Comment by DavePilks** [comment]
Does this mean that you do not have a working sample or that the FireChat.js library will not work in PhoneGap?

**Comment by katowulf** [comment]
We don't have an example of Firechat run on Phonegap. Cheers.
