### ISSUE TITLE
firechat Email & Password Authentication

### ISSUE THREAD

**Issue by vafner** [firebase/firechat#47]
Hi all,

this example show how to authenticate with facebook,
how to use firechat Email & Password Authentication ?

I'm missing something, nothing work for me.
can you please help.

is it not enough to auth to firebase?

<body>
    <div id="firechat-wrapper"></div>
    <script type="text/javascript">
      var chatRef = new Firebase("https://firechat-demo.firebaseio.com");
      var chat = new FirechatUI(chatRef, document.getElementById("firechat-wrapper"));
      chatRef.onAuth(function(authData) {
        if (authData) {
          chat.setUser(authData.uid, "Anonymous" + authData.uid.substr(10, 8));
        } else {
          chatRef.authAnonymously(function(error, authData) {
            if (error) {
              console.log(error);
            }
          });
        }
      });
    </script>
  </body>

**Comment by jwngr** [comment]
Closing due to lack of repro steps. Please provide some code showing what you've tried and also what errors you are getting.
