### ISSUE TITLE
Android source code

### ISSUE THREAD

**Issue by hana9090** [firebase/firechat#53]
Hi guys
it seems that this source code for the web application not for Android version,
So How to get the source code for Android application.

Thanks

**Comment by puf** [comment]
There is no Android version of this specfic chat app. But there are dozens of open-source Android chat apps built on Firebase. For example look at [AndroidChat](https://github.com/firebase/AndroidChat) or the sample app for our [FirebaseUI library](https://github.com/firebase/FirebaseUI-Android). An even better idea might be to take this [codelab that teaches how to build a chat app for Android](https://github.com/firebase/FirebaseUI-Android/tree/master/codelabs/chat).

**Comment by hana9090** [comment]
but there is Android App https://play.google.com/store/apps/details?id=com.opengarden.firechat
is it open source or not?

**Comment by hana9090** [comment]
but there is Android App https://play.google.com/store/apps/details?id=com.opengarden.firechat
is it open source or not?

**Comment by hana9090** [comment]
but there is Android App https://play.google.com/store/apps/details?id=com.opengarden.firechat
is it open source or not?

**Comment by puf** [comment]
That is a completely different Firechat, which has nothing to do with
Firebase. I don't think the source for that is available, but you'd have to
check with Open Garden.

**Comment by hramakrishnappa** [comment]
The new location of the Firebase Android Chat codelab is [this](https://codelabs.developers.google.com/codelabs/firebase-android/index.html?index=..%2F..%2Findex#0)
