### ISSUE TITLE
Push Notifications?

### ISSUE THREAD

**Issue by ashrantk** [firebase/firechat#56]
Is there a way to get push notifications using firechat? or will I have to implement this separately?

**Comment by jwngr** [comment]
[Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) (FCM) currently does not have a cross-browser web push API, so you'll have to do this [from your own server](https://firebase.google.com/docs/cloud-messaging/server) for now. If you are looking for doing push notifications for just Chrome, check out [this doc](https://firebase.google.com/docs/cloud-messaging/chrome/client).

Do keep an eye out on a web push API in the future. No release dates to share yet though.
