### ISSUE TITLE
https://cdn.firebase.com/libs/firechat/2.0.2/firechat.min.css not found

### ISSUE THREAD

**Issue by JeanHuguesRobert** [firebase/firechat#57]
Neither is the .js, min or otherwise

**Comment by greenido** [comment]
Yep. Same to me :(
/cc @abehaskins

**Comment by katowulf** [comment]
Thanks, gents. Abe will get a fix out asap.

**Comment by abehaskins** [comment]
Yep on this - sorry about this. This commit with improper versions has been rolled back and it'll be fixed in the coming days :)
