### ISSUE TITLE
Is Firechat being maintained ?

### ISSUE THREAD

**Issue by GV3** [firebase/firechat#62]
Hello, I'm considering Firebug for a Chat functionality in an App and would like to know if it makes sense to build it based on Firechat. 

Was Firechat not updated lately because it was not necessary or is not being maintained?

Thanks

**Comment by Resonantjacket5** [comment]
See here: https://github.com/firebase/firechat/pull/60

A Firebase employee just had a pull request 5 days ago to move it to firebase 3.0.0. I think they're still waiting on someone to check/review it. 

Also isn't firebug a development tool? not sure how that pertains to chat. Do you mean firebase?

**Comment by GV3** [comment]
Thanks! 
:) 

Let's see if someone from FireBASE reacts to this ; )

**Comment by katowulf** [comment]
> See here: #60
> 
> A Firebase member just had a pull request 5 days ago to move it to firebase 3.0.0. I think they're still waiting on someone to check/review it.
