### ISSUE TITLE
Authentication Disabled due to outdated authentication SDK

### ISSUE THREAD

**Issue by preexo** [firebase/firechat#64]
When trying to authenticate, I get the following message. The example should be updated.

```
We have detected that you are using the v2.x or lower authentication SDKs with a project that was created at console.firebase.google.com. You must use the 3.0.0 or greater authentication SDKs with projects that have been created in the new console.
```

console error
```
Error: Projects created at console.firebase.google.com must use the new Firebase Authentication SDKs available from firebase.google.com/docs/auth/
    at Error (native)
    at http://localhost:3000/app/app.js?hash=8b0f8f97af34cb50e4da678e589f1ccdf1ff9346:2160:17
    at e (http://localhost:3000/app/app.js?hash=8b0f8f97af34cb50e4da678e589f1ccdf1ff9346:1994:176)
.lp?dframe=t&id=528579&pw=dPc9GhJ9xZ&ns=spark-e02a6:5 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```

**Comment by preexo** [comment]
This migration guide will probably help solve the issue: https://firebase.google.com/support/guides/firebase-web#update_your_client_version_numbered

**Comment by stamanker** [comment]
then JS should be fixed; doesn't work

**Comment by jwngr** [comment]
This will be resolved once Firechat supports the Firebase `3.x.x` SDK. The PR to do that is #66 and it hopefully should get deployed next week.

**Comment by jwngr** [comment]
Please upgrade to [the latest `3.0.0` version of Firechat](https://github.com/firebase/firechat/releases/tag/v3.0.0) which now supports the Firebase `3.x.x` SDK. If you use the Firebase `3.x.x` SDK, you will no longer receive this error. Thanks for your patience while we got this figured out and released.
