### ISSUE TITLE
i need example firechat on android platform

### ISSUE THREAD

**Issue by vmintam** [firebase/firechat#75]
Hey Guys,

 I'm in new bie in firebase. I want to build realtime chat application based on android platform. But i only see firechat on web based.

 Anyone help me some example firebase on andoird or ios ?

thanks!

**Comment by paulb777** [comment]
Check out on FriendlyChat - [github repo](https://github.com/firebase/friendlychat), [iOS tutorial](https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#0) , and [Android tutorial](https://codelabs.developers.google.com/codelabs/firebase-android/#0)

**Comment by vmintam** [comment]
thank for reply.

But i want to build chat app that can chat one to one or private group chat as firechat. with your suggestion above, i think not the same with firechat.

Pls help me some examples ?

thanks!

**Comment by puf** [comment]
The codelab builds a basic chat application. You can extend it as needed. There is no equivalent for Firechat for Android, nor has Firechat been updated to the Firebase updates of 2016.
